### ISSUE TITLE
error: Could not compile `amp`.

### ISSUE THREAD

**Issue by mjswensen** [jmacdonald/amp#29] opened 2018-01-26 20:07 UTC
# System details

**macOS version:** 10.13.2
**`brew --version`:** 1.5.2

# Relevant console output

`brew tap jmacdonald/amp && brew install amp`

```
==> cargo build --release
Last 15 lines from /Users/mjswensen/Library/Logs/Homebrew/amp/01.cargo:
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-L" "/usr/local/Cellar/rust/1.23.0/lib/rustlib/x86_64-apple-darwin/lib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/amp-5684d04b7fc51d18.amp0.rcgu.o" "-o" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/amp-5684d04b7fc51d18" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/amp-5684d04b7fc51d18.crate.allocator.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps" "-L" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/build/libgit2-sys-098b69243984559f/out/lib" "-L" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/build/libssh2-sys-98303c5bba578b78/out/lib" "-L" "/usr/local/opt/openssl@1.1/lib" "-L" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/build/termbox-sys-5ebfe27f44b739b6/out/lib" "-L" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/build/miniz-sys-5f639cdb47593da9/out" "-L" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/build/onig_sys-592e34a394c11b60/out/build" "-L" "/usr/local/Cellar/rust/1.23.0/lib/rustlib/x86_64-apple-darwin/lib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libamp-7432a0e02b68ac48.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libtermion-e66342982eee5946.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libscribe-b44ea9dbe935b3a9.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/liberror_chain-225ec74a61477073.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libgit2-e806379ea48de4e1.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libapp_dirs-b4875c00acf3bf7f.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libunicode_segmentation-7fb605f832b80451.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/liberror_chain-065b0874ae3caa9b.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libregex-86df2a7120745290.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libaho_corasick-7d7441f3cb157eac.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libutf8_ranges-042776cb20b1a62f.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libclipboard-132e5874f63c62e5.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libsmallvec-88250473b26dac28.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libregex_syntax-f8ef34fc8d2d89e1.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libpad-af40836f5eaf8ddb.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libunicode_width-7b0c84f52388a24c.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/liburl-2a3990a068032482.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libidna-59724bb287671349.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libunicode_normalization-01398635c2560b4f.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libunicode_bidi-af83364affc0aad8.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libmatches-b6e54ecbffce67f9.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libobjc_foundation-a22831537a649bcc.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libblock-19e62031ef3f1e48.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/liblibgit2_sys-044b05748c92d252.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libcurl_sys-87c3162b3db93a2a.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/liblibssh2_sys-c9c25b68c0e31c1d.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libopenssl_sys-eb3619330759a60e.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/liblibz_sys-48ec0f882056f2ce.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libluthor-d6675f0d534f4cc8.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libthread_local-648620192c2d125b.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libthread_id-19797651374cf87b.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libbloodhound-f5941a1ad09c0c4e.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libwalkdir-ff2555de033c09b7.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libsame_file-8e6b939923e1fb95.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libglob-6fb1885ffa3defb5.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libfragment-1d65161d5f462746.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libbacktrace-3570945de16fa196.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/librustc_demangle-0ed373e48e5e3deb.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libcfg_if-d8eba8e635f4be3d.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libobjc_id-2415fcab6f5e9cab.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libobjc-21f00305b3ffb90d.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libmalloc_buf-9246794bd36eb191.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libpercent_encoding-932723c0adffc35b.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/librustbox-ee6c2b81ef82355f.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libbitflags-9a937c48e125844f.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libtermbox_sys-f7025138e5b01205.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libgag-dbebac7fac1a4dea.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libtempfile-fc9cced3a12b7f56.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libbitflags-4310ca2a84378df5.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libmemchr-a2856ec26b17be6f.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libsyntect-74223406047b74d1.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libserde_json-e6077b509e6c59e2.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libdtoa-6c1094f9d3d4440c.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libitoa-4c01e9ea70b8a7c6.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libfnv-286308532cdbca70.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libflate2-1e11f7b74e22a1fd.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libminiz_sys-6d16296bbf0b06d8.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libbitflags-1e9d572282c5a94a.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libbincode-c9566417e132eaf5.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libplist-89cf05399e9527fb.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libserde-8d1ba06d8375e362.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libxml-eda2410d6ae7dc74.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libbitflags-ef1b1baab8156dde.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libchrono-57822d6f738fdba9.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libnum-d891251d7fa3f919.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libnum_rational-4304f8d6ff6439bf.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libnum_bigint-e8529184897aec18.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/librand-ee817cc143ee39ae.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libnum_complex-64b83890e93f9c67.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/librustc_serialize-940c200299c36a78.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libtime-1958e4cbfc30c043.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libbase64-d482b5d783df9630.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libbyteorder-c446b2ff9b4b168a.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libregex_syntax-46a9ba67f277fd26.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libonig-ab40b979b6814a22.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libonig_sys-4fb6d4e47266fa62.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/liblibc-f71a304c9897aecb.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/liblazy_static-8e83c3903dca9b04.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libbitflags-2ebb9d5cc71e63bc.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libyaml_rust-faebe390f78fceba.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libwalkdir-97a598e206931474.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libsame_file-88db3cc98d177498.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libsafemem-5c35b304236da68d.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libnum_iter-fcd5accb61e45f82.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libnum_integer-3ff2825516f38b16.rlib" "/private/tmp/amp-20180126-92710-153fq2v/amp-0.3.2/target/release/deps/libnum_traits-7f37b0f3da3c490c.rlib" "/usr/local/Cellar/rust/1.23.0/lib/rustlib/x86_64-apple-darwin/lib/libstd-1066840d7e6956ae.rlib" "/usr/local/Cellar/rust/1.23.0/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-21f981c647b7bf0e.rlib" "/usr/local/Cellar/rust/1.23.0/lib/rustlib/x86_64-apple-darwin/lib/liballoc_jemalloc-bf83ac3154b02140.rlib" "/usr/local/Cellar/rust/1.23.0/lib/rustlib/x86_64-apple-darwin/lib/libunwind-48dcdd790a8dd163.rlib" "/usr/local/Cellar/rust/1.23.0/lib/rustlib/x86_64-apple-darwin/lib/liballoc_system-1071ae993f37c69b.rlib" "/usr/local/Cellar/rust/1.23.0/lib/rustlib/x86_64-apple-darwin/lib/liblibc-ecd13f184f8fe531.rlib" "/usr/local/Cellar/rust/1.23.0/lib/rustlib/x86_64-apple-darwin/lib/liballoc-52ac869ede6a8471.rlib" "/usr/local/Cellar/rust/1.23.0/lib/rustlib/x86_64-apple-darwin/lib/libstd_unicode-295411b4a3449f1c.rlib" "/usr/local/Cellar/rust/1.23.0/lib/rustlib/x86_64-apple-darwin/lib/libcore-f9d635782e34e49d.rlib" "/usr/local/Cellar/rust/1.23.0/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-17b814a5b2f07f8f.rlib" "-framework" "AppKit" "-framework" "Foundation" "-l" "System" "-l" "iconv" "-framework" "Security" "-framework" "CoreFoundation" "-l" "curl" "-l" "ssl" "-l" "crypto" "-l" "z" "-l" "objc" "-l" "objc" "-l" "objc" "-l" "System" "-l" "resolv" "-l" "pthread" "-l" "c" "-l" "m"
  = note: Undefined symbols for architecture x86_64:
            "_OPENSSL_add_all_algorithms_noconf", referenced from:
                _libssh2_init in liblibssh2_sys-c9c25b68c0e31c1d.rlib(global.c.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


error: aborting due to previous error

error: Could not compile `amp`.
```

Let me know if you need any additional information!

**Comment by mjswensen** [comment] 2018-01-26 20:35
Update: I was able to compile from source successfully, so perhaps the problem is with the brew installer.

**Comment by jmacdonald** [comment] 2018-01-26 20:36
Thanks for the info! Can you please paste the output of the following?

`brew list --versions`

**Comment by mjswensen** [comment] 2018-01-26 20:37
No problem:

```
adns 1.5.1
asciinema 1.4.0
atk 2.24.0
atkmm 2.24.2
autoconf 2.69
automake 1.15.1 1.15
avr-binutils 2.29
avr-gcc 7.2.0
avrdude 6.3
bdw-gc 7.6.0
boost 1.64.0_1
boost-build 2016.03
cairo 1.14.10
cairomm 1.12.2
cmake 3.10.2
coreutils 8.28_1 8.27
deis 2.18.0
dfu-programmer 0.7.2
erlang 20.1.4 19.3
ffmpeg 3.3.2
fontconfig 2.12.4
freetype 2.8
fzy 0.8
gcc-arm-none-eabi 20160928
gdbm 1.14 1.13
gdk-pixbuf 2.36.8
gettext 0.19.8.1
glib 2.52.3 2.54.1
glib-networking 2.50.0
glibmm 2.52.0
gmp 6.1.2 6.1.2_1
gnu-sed 4.4
gnupg 2.1.21
gnutls 3.5.14 3.5.12
gobject-introspection 1.52.1_1
graphite2 1.3.10
grip 4.4.0
gsettings-desktop-schemas 3.24.0
gsl 2.4
gtk+ 2.24.31_1
gtkmm 2.24.5
harfbuzz 1.4.8
heroku 5.8.5
hicolor-icon-theme 0.15
icu4c 58.2 59.1
inkscape 0.92.2
intltool 0.51.0
jpeg 9b 8d
keychain 2.8.3
kubernetes-cli 1.7.3
kubetail 1.4.1
lame 3.99.5
libassuan 2.4.3_1
libdvdcss 1.4.0
libelf 0.8.13_1
libevent 2.1.8
libffi 3.2.1
libftdi0 0.20
libgcrypt 1.7.6
libgpg-error 1.27
libksba 1.3.5
libmpc 1.1.0
libpng 1.6.31 1.6.34 1.6.29
libsigc++ 2.10.0
libsoup 2.58.2
libssh2 1.8.0
libtasn1 4.12 4.10
libtiff 4.0.8 4.0.8_3 4.0.8_5
libtool 2.4.6_1
libunistring 0.9.7
libusb 1.0.21
libusb-compat 0.1.5_1
libxml2 2.9.4_3
libyaml 0.1.7
little-cms 1.19_1
little-cms2 2.8_1
lua 5.2.4_4
lzip 1.19
mongodb 3.4.4
mpfr 4.0.0
nettle 3.3
nginx 1.12.2_1
node 8.4.0
npth 1.4
openjpeg 2.2.0
openssl 1.0.2n 1.0.2k 1.0.2l 1.0.2m
openssl@1.1 1.1.0g 1.1.0f
p11-kit 0.23.7 0.23.5
pango 1.40.9
pangomm 2.40.1
parallel 20171222
pcre 8.41 8.40
perl 5.26.1 5.24.1
pinentry 1.0.0
pixman 0.34.0_1
pkg-config 0.29.2
poppler 0.57.0_1
popt 1.16
postgresql 9.6.2
potrace 1.14
python 2.7.14 2.7.13 2.7.13_1
python3 3.6.2 3.6.4_1
rabbitmq 3.6.14 3.6.9
readline 7.0.3_1
redis 4.0.2
ripgrep 0.5.1
ruby 2.4.1_1 2.4.2_1
rust 1.23.0
shared-mime-info 1.8_1
sqlite 3.21.0 3.18.0 3.20.0
tmux 2.6 2.3_3
vala 0.36.4
vim 8.0.1250 8.0.0562
wxmac 3.0.2_4 3.0.3.1_1
x264 r2748
xvid 1.3.4
xz 5.2.3
zsh 5.3.1
```

**Comment by jmacdonald** [comment] 2018-01-26 20:54
Ace, this is helpful. I've been able to reproduce it, and it seems having `openssl@1.1` installed is to blame. Odd, because the `openssl` libs are the ones linked in `/usr/local` and I've set all of these:

```
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"
export OPENSSL_ROOT_DIR=/usr/local/opt/openssl
export PKG_CONFIG_PATH=/usr/local/opt/openssl@1.0/lib/pkgconfig
```

I'll press this a little more later tonight to see if I can get the linker to point to those libs.

**Comment by mjswensen** [comment] 2018-01-26 21:06
Super weird. Thanks for looking into it. No rush.

**Comment by bnsv** [comment] 2018-01-27 08:11
Hi, I failed to install it too after long waiting the compilation process, i'm using openSuse.  here is my listing. 
`
me@my-pc:~/amp> cargo install --git https://github.com/jmacdonald/amp/ --tag 0.3.2
    Updating git repository `https://github.com/jmacdonald/amp/`
  Installing amp v0.3.2 (https://github.com/jmacdonald/amp/?tag=0.3.2#5ec29b3e)
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/jmacdonald/termion`
 Downloading pad v0.1.4
 Downloading rustbox v0.9.0 
 .
 .
 . 
 Downloading openssl-probe v0.1.2
 Downloading openssl-sys v0.9.24
 Downloading x11-clipboard v0.1.4
 Downloading xcb v0.7.7
   Compiling unicode-segmentation v1.0.3
   Compiling same-file v1.0.2
   Compiling serde v1.0.27 
 .
 .
 .
   Compiling libssh2-sys v0.2.6
   Compiling libgit2-sys v0.6.19
   Compiling onig_sys v65.0.1
error: failed to run custom build command for `openssl-sys v0.9.24`
process didn't exit successfully: `/tmp/cargo-install.5kMYfcNXQyAu/release/build/openssl-sys-f927d495753f90df/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
cargo:rerun-if-env-changed=OPENSSL_DIR
run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit code: 1\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'openssl\' found\n"

--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

    $HOST = x86_64-unknown-linux-gnu
    $TARGET = x86_64-unknown-linux-gnu
    openssl-sys = 0.9.24

', /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.24/build.rs:210:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `amp v0.3.2 (https://github.com/jmacdonald/amp/?tag=0.3.2#5ec29b3e)`, intermediate artifacts can be found at `/tmp/cargo-install.5kMYfcNXQyAu`

Caused by:
  build failed 
`

**Comment by timotk** [comment] 2018-01-27 12:35
On Ubuntu I solved it with 
```
sudo apt-get install libssl-dev
```
as per instructions on https://github.com/sfackler/rust-openssl, which is linked in the error:
```
If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.
```

**Comment by bnsv** [comment] 2018-01-29 10:13
i tried `sudo zypper install libssl-dev ` have no luck. The problem is likely in opensuse side or mine.
`
Loading repository data... 
Reading installed packages...    
'libssl-dev' not found in package names. Trying capabilities.
No provider of 'libssl-dev' found. 
Resolving package dependencies...  
Nothing to do. 
`

**Comment by LeakyBucket** [comment] 2018-01-29 14:21
For OpenSSL issues on OSX with the brew installed SSL I did the following and was able to build:

```
export OPENSSL_INCLUDE_DIR=$(brew --prefix openssl)/include
export OPENSSL_LIB_DIR=$(brew --prefix openssl)/lib
```

**Comment by jmacdonald** [comment] 2018-01-29 14:27
For OS X users, see [this](https://github.com/Homebrew/homebrew-core/pull/22441) homebrew-core PR to add `amp` to the list of built-in formulae, which will provide binary releases.

As for Linux distros, work on [binary releases](https://github.com/jmacdonald/amp/issues/32) is in progress.

Not to say we shouldn't fix building from source, but this will give folks a viable alternative when building is problematic.

**Comment by pertrai1** [comment] 2018-01-29 21:12
@jmacdonald I am looking forward to getting this installed on my Mac. What exactly are the instructions for installation at this time while we wait for the PR in homebrew-core?

**Comment by jmacdonald** [comment] 2018-01-29 22:41
Sadly, at this point, the only workaround for this issue that I've found to work is to uninstall the `openssl@1.1` formula, compile Amp, and then re-install `openssl@1.1`. None of the aforementioned environment variables have gotten the linker on my machine to pick up the openssl 1.0 libs.

Outside of the Homebrew route, I'm working on binary releases in general. Once those are available, I'll update all of the various compilation discussions to let folks know where they can be found.

Thanks for being patient! 🙂

**Comment by jmacdonald** [comment] 2018-01-30 04:18
I've added binaries to the [0.3.2 release page](https://github.com/jmacdonald/amp/releases/tag/0.3.2) to provide a workaround while we wait for `amp` to be merged into homebrew-core.

You'll still need the runtime dependencies as specified in the [installation instructions](https://amp.rs/docs/installation#dependencies), if they're not already installed. We're also automating binary builds at the moment; if you're interested in following that, see #32.

I'll update the folks in this thread once `amp` is available as a binary through Homebrew.

**Comment by jmacdonald** [comment] 2018-02-10 02:19
I've addressed the Homebrew build error; a `brew update && brew install amp` should do the trick for folks on macOS. If people are having issues building Amp on their Linux distro of choice (other than Arch Linux, which is already supported via AUR), please open a separate issue and we'll focus on your particular platform!

**Closed by jmacdonald** 2018-02-10 02:19 UTC
