### ISSUE TITLE
onig/onig_sys extremely outdated in Cargo deps

### ISSUE THREAD

**Issue by DomT4** [jmacdonald/amp#222] opened 2021-04-25 21:07 UTC
Hi there,

I notice `amp` is using quite an outdated version of `onig` and `onig_sys`, 3.2.2 and 68.0.1 respectively from ~2018, when the current versions are 6.1.1 & 69.6.0. `onig_sys` in particular prior to version 4.0.0 needed `cmake` to compile, which can be problematic on macOS platforms running Apple Silicon. The `cc` crate also needs updating for full Apple Silicon support.

I was wondering if you'd be willing to update the Cargo dependencies so that Homebrew can package `amp` successfully on ARM macOS without having to manage the dependencies ourselves.

Thanks!

Ref: https://github.com/Homebrew/homebrew-core/pull/75790

**Comment by jmacdonald** [comment] 2024-01-08 13:35
Hi there @DomT4! Sorry for the lengthy gap to responding. 😅 I've just landed major upgrades to syntect, which includes a bump to `onig`/`onig_sys`. I'm planning on cutting a `0.7.0` release in a week or so, after using the editor regularly to make sure there are no regressions. Anything else you need on my end?

**Comment by timsutton** [comment] 2024-01-24 00:40
Since we have just bumped to 0.7.0 in homebrew-core, I think we can close this issue!

**Comment by jmacdonald** [comment] 2024-01-24 01:37
@timsutton thank you for keeping that Homebrew formula up to date! 🍻

**Closed** 2024-01-24 01:38 UTC
