### ISSUE TITLE
Slow search 

### ISSUE THREAD

**Issue by Jordin22** [jmacdonald/amp#69] opened 2018-02-13 23:07 UTC
When I press the space bar to open the search function, amp seems to execute a search.
Since this is started on my home directory, this is extremely slow.

Amp should not execute a search before the user can enter a search term

**Comment by jedahan** [comment] 2018-02-14 16:49
I think this is a duplicate of #68 - though it would be hard to glean from the issue title since there is no mention of keywords slow and search :)

**Comment by jmacdonald** [comment] 2018-02-15 02:47
That it is, @jedahan. :)

It's the indexing that's "slow". I'm not convinced that searching across an entire user's home directory is a path we want to optimize for, but running the indexing in the main event loop is an improvement I've been meaning to make for a while. At very least, people should be made aware and be able to exit open mode / cancel the indexing.

I'm a little short on time at the moment, but this usability issue has cropped up several times now. I'll be prioritizing that change next week; keep an eye on that issue for a fix!

**Closed by jmacdonald** 2018-02-15 02:47 UTC
